name: CI

on:
  push:
    branches:
      - main  # Déclenche le workflow uniquement lorsque des modifications sont poussées vers la branche "master"

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'  # Vérifie si la branche est bien "master"
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Installer PHP (si nécessaire)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Utilise la version PHP adaptée à ton projet
          extensions: mbstring, xml, bcmath, zip, curl, gd, opcache

      # 3. Installer Composer (si nécessaire)
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      # 4. Installer les dépendances PHP avec Composer
      - name: Install dependencies
        run: |
          cd ${{ secrets.PROJECT_PATH }}
          composer install --prefer-
