name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, bcmath, zip, curl, gd, opcache

    # Install dependencies
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    # Set up environment file
    - name: Set up .env
      run: cp .env.example .env

    # Generate application key
    - name: Generate app key
      run: php artisan key:generate

    # Cache configuration and routes
    - name: Cache config and routes
      run: |
        php artisan config:cache
        php artisan route:cache

    # Run database migrations (optional)
    - name: Run migrations
      run: |
        php artisan migrate --env=testing --force

    # Run tests
    - name: Run tests
      run: |
        ./vendor/bin/phpunit --configuration phpunit.xml

    # Clear caches
    - name: Clear cache
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
